// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyWingViewer.Services;

#nullable disable

namespace SkyWingViewer.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260622193935_Fix LibraryId default value in AssetTable to 0")]
    partial class FixLibraryIddefaultvalueinAssetTableto0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("SkyWingViewer.Services.AssetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CapturedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationFileTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddedTime");

                    b.HasIndex("CapturedTime");

                    b.HasIndex("CreationFileTime");

                    b.HasIndex("FileSize");

                    b.HasIndex("LibraryId");

                    b.HasIndex("ModifiedTime");

                    b.HasIndex("Name");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasFilter("[LibraryId] IS NULL");

                    b.HasIndex("Rating");

                    b.HasIndex("LibraryId", "ParentPath");

                    b.HasIndex("Path", "LibraryId")
                        .IsUnique();

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("SkyWingViewer.Services.AssetTagPairEntity", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId", "TagId");

                    b.HasIndex("TagId", "AssetId");

                    b.ToTable("AssetTagPair");
                });

            modelBuilder.Entity("SkyWingViewer.Services.LibraryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RootPath")
                        .IsUnique();

                    b.ToTable("Library");
                });

            modelBuilder.Entity("SkyWingViewer.Services.TagsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SkyWingViewer.Services.AssetEntity", b =>
                {
                    b.HasOne("SkyWingViewer.Services.LibraryEntity", "Library")
                        .WithMany("Assets")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("SkyWingViewer.Services.AssetTagPairEntity", b =>
                {
                    b.HasOne("SkyWingViewer.Services.AssetEntity", "AssetEntity")
                        .WithMany("AssetTagPairs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyWingViewer.Services.TagsEntity", "TagsEntity")
                        .WithMany("AssetTagPairs")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetEntity");

                    b.Navigation("TagsEntity");
                });

            modelBuilder.Entity("SkyWingViewer.Services.AssetEntity", b =>
                {
                    b.Navigation("AssetTagPairs");
                });

            modelBuilder.Entity("SkyWingViewer.Services.LibraryEntity", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("SkyWingViewer.Services.TagsEntity", b =>
                {
                    b.Navigation("AssetTagPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
