// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyWingViewer.Services;

#nullable disable

namespace SkyWingViewer.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("SkyWingViewer.Services.AssetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CapturedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreationFileTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddedTime");

                    b.HasIndex("CapturedTime");

                    b.HasIndex("CreationFileTime");

                    b.HasIndex("FileSize");

                    b.HasIndex("ModifiedTime");

                    b.HasIndex("Name");

                    b.HasIndex("ParentPath");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("Rating");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("SkyWingViewer.Services.AssetTagPairEntity", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId", "TagId");

                    b.HasIndex("TagId", "AssetId");

                    b.ToTable("AssetTagPair");
                });

            modelBuilder.Entity("SkyWingViewer.Services.TagsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SkyWingViewer.Services.AssetTagPairEntity", b =>
                {
                    b.HasOne("SkyWingViewer.Services.AssetEntity", "AssetEntity")
                        .WithMany("AssetTagPairs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyWingViewer.Services.TagsEntity", "TagsEntity")
                        .WithMany("AssetTagPairs")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetEntity");

                    b.Navigation("TagsEntity");
                });

            modelBuilder.Entity("SkyWingViewer.Services.AssetEntity", b =>
                {
                    b.Navigation("AssetTagPairs");
                });

            modelBuilder.Entity("SkyWingViewer.Services.TagsEntity", b =>
                {
                    b.Navigation("AssetTagPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
